apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/part-of: devsecops-plateform
    app.kubernetes.io/category: kubernetes-dashboard
    app.kubernetes.io/tier: monitoring  
    app.kubernetes.io/managed-by: argocd
    environment: production
    plateform.io/wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/resources/limits
        - /spec/template/spec/containers/0/resources/requests
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/template/spec/containers/0/resources/limits
        - /spec/template/spec/containers/0/resources/requests
  source:
    repoURL: https://github.com/Niteshkushwaha9595fbd/argocd-tools.git
    targetRevision: main
    path: tools/headlamp
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - Validate=false
      - PruneLast=true
      - Replace=true
      - ApplyOutOfSyncOnly=false
      - RespectIgnoreDifferences=false
      - ServerSideApply=false
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m"