apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
	- harbor-namespace.yaml
	- vault-namespace.yaml
	- agic-namespace.yaml

commonLabels:
	app.kubernetes.io/managed-by: argocd
	app.kubernetes.io/component: namespaces

