apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources included in this kustomization
resources:
  - agic-namespace.yaml
  - deployment.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - sa.yaml
  - secret.yaml

# set namespace for all resources
namespace: ingress-azure

# commonLabels:
#   app.kubernetes.io/managed-by: argocd
#   app.kubernetes.io/component: agic

images:
  - name: mcr.microsoft.com/azure-application-gateway/kubernetes-ingress
    newName: mcr.microsoft.com/azure-application-gateway/kubernetes-ingress
    newTag: 1.7.2

replicas:
  - name: ingress-azure-pod
    count: 2
