apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- secret.yaml
- agic-namespace.yaml

namespace: ingress-azure

images:
- name: mcr.microsoft.com/azure-application-gateway/kubernetes-ingress
  newTag: 1.7.2

replicas:
- name: ingress-azure-pod
  count: 1
