apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - sa.yaml
  - secret.yaml

namespace: ingress-azure

images:
  - name: mcr.microsoft.com/azure-application-gateway/kubernetes-ingress
    newName: mcr.microsoft.com/azure-application-gateway/kubernetes-ingress
    newTag: 1.7.2

replicas:
  - name: ingress-azure-pod
    count: 1
