apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdo-agent
  namespace: azdo-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdo-agent
  template:
    metadata:
      labels:
        app: azdo-agent
    spec:
      containers:
      - name: azdo-agent
        image: mcr.microsoft.com/azure-pipelines/vsts-agent:ubuntu-22.04
        env:
        - name: AZP_URL
          value: https://dev.azure.com/ORG_NAME
        - name: AZP_POOL
          value: kubernetes-pool
        - name: AZP_AGENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azdo-agent-secret
              key: AZP_TOKEN
