apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-agent
  namespace: azure-devops-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdo-agent
  template:
    metadata:
      labels:
        app: azdo-agent
    spec:
      serviceAccountName: default

      # Pod runs as root to avoid permission issues
      securityContext:
        runAsNonRoot: false

      containers:
      - name: azdo-agent
        image: docker.io/niteshkushwaha95/azure-devops-agent:arm64-1.0.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: azp-data
            mountPath: /azp
          - name: docker-sock
            mountPath: /var/run/docker.sock  # Mount host Docker socket
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdo-agent-secret
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdo-agent-secret
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdo-agent-secret
                key: AZP_POOL
          - name: AZP_AGENT_NAME
            value: "k8s-agent-$(HOSTNAME)"
          - name: DOCKER_HOST
            value: unix:///var/run/docker.sock  # Use host Docker
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          exec:
            command: ["bash", "-c", "pgrep -f Agent.Listener"]
          initialDelaySeconds: 60
          periodSeconds: 60
        readinessProbe:
          exec:
            command: ["bash", "-c", "pgrep -f Agent.Listener"]
          initialDelaySeconds: 30
          periodSeconds: 30
